// Command docscatalog renders the builtin rule catalog as the JSON data file
// that the documentation site's rules page reads.
//
// The page has to name the rules that ship, not a table kept by hand. So the
// rows come from a real engine built with default options. With --output the
// command writes the file. With --check it holds the committed file against
// fresh bytes. CI runs that check, so a stale page fails the build.
//
// This is a developer command. It is not part of the public API, and the
// documentation site is the only consumer of its output.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/stokaro/unswell"
	"github.com/stokaro/unswell/rule"
)

// schemaID names the shape of the generated file. The site reads it before
// rendering, so a future change of shape is a visible mismatch rather than a
// page that silently drops half its columns.
const schemaID = "unswell-docs-rules-catalog-v1"

// catalog is the whole generated document.
type catalog struct {
	Schema    string   `json:"schema"`
	RuleCount int      `json:"rule_count"`
	Families  []family `json:"families"`
}

// family collects the rules sharing one identifier prefix, such as filler or
// repetition. It is the reader's grouping. It is not the descriptor's
// correlation group, which decides shared score caps and is reported per rule.
type family struct {
	Name  string  `json:"name"`
	Rules []entry `json:"rules"`
}

// entry is one rule as the page presents it.
type entry struct {
	ID          string   `json:"id"`
	Version     string   `json:"version"`
	Status      string   `json:"status"`
	Group       string   `json:"group"`
	Scope       string   `json:"scope"`
	Contexts    []string `json:"contexts"`
	Enabled     bool     `json:"enabled"`
	Severity    string   `json:"severity"`
	Gate        string   `json:"gate"`
	Weight      int      `json:"weight"`
	Cap         int      `json:"cap"`
	Summary     string   `json:"summary"`
	Description string   `json:"description"`
	Limitations string   `json:"limitations"`
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintf(os.Stderr, "docscatalog: %v\n", err)
		os.Exit(1)
	}
}

func run(arguments []string, out *os.File) error {
	flags := flag.NewFlagSet("docscatalog", flag.ContinueOnError)
	output := flags.String("output", "docs/site/src/data/rules-catalog.json", "path of the generated catalog file")
	check := flags.Bool("check", false, "compare the existing file with the generated bytes instead of writing it")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %s", strings.Join(flags.Args(), " "))
	}
	rendered, err := render()
	if err != nil {
		return err
	}
	if *check {
		return compare(*output, rendered, out)
	}
	return write(*output, rendered, out)
}

// render builds the engine and serializes its catalog.
func render() ([]byte, error) {
	engine, err := unswell.New(unswell.Options{})
	if err != nil {
		return nil, fmt.Errorf("construct the engine: %w", err)
	}
	document := build(engine.Catalog())
	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode the catalog: %w", err)
	}
	return append(encoded, '\n'), nil
}

// build groups descriptors by identifier prefix and orders everything so the
// same engine always renders the same bytes.
func build(descriptors []rule.Descriptor) catalog {
	byFamily := map[string][]entry{}
	for _, descriptor := range descriptors {
		name := familyOf(descriptor.ID)
		byFamily[name] = append(byFamily[name], convert(descriptor))
	}
	names := make([]string, 0, len(byFamily))
	for name := range byFamily {
		names = append(names, name)
	}
	sort.Strings(names)
	families := make([]family, 0, len(names))
	for _, name := range names {
		rules := byFamily[name]
		sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
		families = append(families, family{Name: name, Rules: rules})
	}
	return catalog{Schema: schemaID, RuleCount: len(descriptors), Families: families}
}

// familyOf takes the identifier prefix. An identifier without a dot is its own
// family rather than an error: the page still has somewhere to put it.
func familyOf(id string) string {
	prefix, _, found := strings.Cut(id, ".")
	if !found || prefix == "" {
		return id
	}
	return prefix
}

func convert(descriptor rule.Descriptor) entry {
	contexts := append([]string(nil), descriptor.Contexts...)
	sort.Strings(contexts)
	return entry{
		ID:          descriptor.ID,
		Version:     descriptor.Version,
		Status:      descriptor.Status,
		Group:       descriptor.Group,
		Scope:       descriptor.Scope,
		Contexts:    contexts,
		Enabled:     descriptor.Defaults.Enabled,
		Severity:    descriptor.Defaults.Severity,
		Gate:        descriptor.Defaults.Gate,
		Weight:      descriptor.Defaults.Score.Weight,
		Cap:         descriptor.Defaults.Score.Cap,
		Summary:     descriptor.Summary,
		Description: descriptor.Description,
		Limitations: descriptor.Limitations,
	}
}

func write(path string, rendered []byte, out *os.File) error {
	if directory := filepath.Dir(path); directory != "" {
		if err := os.MkdirAll(directory, 0o750); err != nil {
			return err
		}
	}
	if err := os.WriteFile(path, rendered, 0o600); err != nil {
		return err
	}
	_, err := fmt.Fprintf(out, "wrote %s (%d bytes)\n", path, len(rendered))
	return err
}

// compare reports a stale or missing file as a failure. The message names the
// command that fixes it, because the reader of a red build is usually not the
// author of this file.
func compare(path string, rendered []byte, out *os.File) error {
	// #nosec G304 -- The path is a developer flag naming the generated file in this repository.
	existing, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("%s is missing; run: go run ./cmd/docscatalog --output %s", path, path)
	}
	if err != nil {
		return err
	}
	if !bytes.Equal(existing, rendered) {
		return fmt.Errorf("%s is stale; run: go run ./cmd/docscatalog --output %s", path, path)
	}
	_, err = fmt.Fprintf(out, "%s matches the engine catalog\n", path)
	return err
}
