#!/usr/bin/env python3
"""Generate the whole-page results tables and missed-event repair inventory."""

import argparse
from pathlib import Path

from evaluate import evaluate, load, read, write


def percent(value):
    return 'n/a' if value is None else f'{100 * value:.1f}%'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('record', type=Path)
    args = parser.parse_args()
    root = args.record
    result = evaluate(root)
    manifest, pages, files, annotations, defects = load(root)
    write(root / 'results.json', result)
    lines = ['# Whole-page recall results', '',
             'Generated by `tools/render.py` from the frozen sources, annotations, public-engine reports and disposition ledger.', '',
             '**Auxiliary single-assistant review. These are development labels, not independent human qualification or an authorship experiment.**', '',
             '## Frozen-event recall', '',
             '| Profile | Cohort | Pages | Detected / defects | Recall | Findings | Actionable / nonactionable / uncertain |',
             '| --- | --- | ---: | ---: | ---: | ---: | --- |']
    for profile, report in result['profiles'].items():
        for cohort, group in report['groups'].items():
            d=group['dispositions']
            lines.append(f'| {profile} | {cohort} | {group["pages"]} | {group["detected"]} / {group["defects"]} | {percent(group["recall"])} | {group["findings"]} | {d.get("actionable",0)} / {d.get("nonactionable",0)} / {d.get("uncertain",0)} |')
    lines += ['', 'Actionability includes ten separately recorded, detector-assisted complexity events. Those events are excluded from the frozen recall denominator. Two diagnostics address one of them. Findings can overlap a missed event without diagnosing it; a length warning does not earn credit for empty framing.', '',
              'Both whole-source runs completed with exit 0 and no rule abstentions. A passing gate is not a clean-text label.', '',
              '## Categories (same frozen recall in both profiles)', '',
              '| Category | Ptah sample | Historical sample | Exposed anchors |', '| --- | ---: | ---: | ---: |']
    groups=result['profiles']['technical']['groups']
    for category in sorted(next(iter(groups.values()))['categories']):
        cells=[]
        for key in ['ptah-sample','historical-sample','ptah-exposed_anchor']:
            c=groups[key]['categories'][category];cells.append(f'{c["detected"]} / {c["defects"]}')
        lines.append('| '+category+' | '+' | '.join(cells)+' |')
    lines += ['', '## Sampling sensitivity', '',
              'Paired page bootstrap: 2,000 replicates, seed 9172026, resampled within the fixed format/length cells. The same page draw applies to numerator and denominator. These intervals show only variation among the reviewed pages, not label uncertainty or population performance. Ptah is one repository.', '']
    for key in ['ptah-sample','historical-sample']:
        u=groups[key]['sensitivity'];lo,hi=u['page_bootstrap_percentile_95'];a,b=u['leave_one_page_out_range']
        lines.append(f'- {key}: bootstrap interval {percent(lo)}–{percent(hi)}; leave-one-page-out range {percent(a)}–{percent(b)}.')
    lines += ['', 'A 0–0 bootstrap interval occurs when no sampled event was detected; it does **not** establish a true population recall of zero. The two exposed anchors were not randomly selected and receive no interval.', '',
              '## Provisional clean-unit alarms', '',
              'An assessment paragraph is provisionally clean only when it overlaps no frozen defect, uncertain annotation, post-freeze positive or unresolved diagnostic. Counts include every related finding location. These are auxiliary label-dependent alarm rates, not qualified false-positive rates. The minimum-word rows are descriptive sensitivity analyses: short headings and generated table cells otherwise dominate the denominator.', '',
              '| Profile | Cohort | Minimum prose words | Alarmed / provisional clean units |', '| --- | --- | ---: | ---: |']
    for profile,r in result['profiles'].items():
        c=r['provisional_clean_paragraphs']
        for cohort in ['ptah','historical']:
            for n in [1,20,40]:
                prefix=cohort+'_min'+str(n)
                lines.append(f'| {profile} | {cohort} | {n} | {c.get(prefix+"_alarmed",0)} / {c.get(prefix+"_units",0)} |')
    lines += ['', '## Page results', '',
              'All selected files have consecutive coverage records spanning their complete bytes. Source parsing excludes code and metadata; imported component output and image text are not expanded. See protocol scope limitations.', '',
              '| Page | Source | Cohort | Prose words | Detected / defects | Technical findings | Strict findings |', '| --- | --- | --- | ---: | ---: | ---: | ---: |']
    strict={r['page']:r for r in result['profiles']['strict']['pages']}
    for r in result['profiles']['technical']['pages']:
        p=pages[r['page']];label=p['repository']+'/'+p['original_path']
        lines.append(f'| {r["page"]} | [{label}]({p["reference"]}) | {r["cohort"]} / {r["selection"]} | {r["words"]} | {r["detected"]} / {r["defects"]} | {r["findings"]} | {strict[r["page"]]["findings"]} |')
    (root/'RESULTS.md').write_text('\n'.join(lines)+'\n')
    missed={eid for p in result['profiles']['technical']['pages'] for eid in p['missed']}
    lines=['# Missed editorial events', '',
           'Generated from the frozen annotations. Both profiles miss the same events. Quotations retain the source wording; line numbers and links refer to the pinned original. The proposed edits are review suggestions, not automatic rewrites.', '']
    for eid,e in sorted(defects.items()):
        if eid not in missed:
            continue
        p=pages[e['page']];source=files[p['path']];line=source[:e['targets'][0]['start']].count(b'\n')+1
        lines += [f'## {eid}: {e["category"]}', '',f'[{p["repository"]}/{p["original_path"]}, line {line}]({p["reference"]}#L{line}) — {p["selection"]}.', '']
        for t in e['targets']:
            lines += ['> '+' '.join(t['quote'].split()), '']
        lines += [e['rationale'],'', '**Proposed repair:** '+e['proposed_edit'], '']
    (root/'MISSES.md').write_text('\n'.join(lines).rstrip()+'\n')
    print('Generated results and',len(missed),'missed-event records.')


if __name__ == '__main__':
    main()
