package extract

import (
	"strings"

	"github.com/stokaro/unswell/document"
)

// commonDirectives are comment prefixes that tools of every language read as
// instructions: license identifiers, generated-file markers, editor modelines,
// source encodings and Unswell's own suppressions.
var commonDirectives = []string{
	"-*-", "@generated", "Code generated", "SPDX-", "coding:", "coding=", "unswell-", "vi:", "vim:",
}

var (
	scriptDirectives = []string{
		"@flow", "@jsx", "@jsxFrag", "@jsxImportSource", "@jsxRuntime", "@ts-check", "@ts-expect-error", "@ts-ignore",
		"@ts-nocheck", "biome-ignore", "c8 ignore", "deno-fmt-ignore", "deno-lint-ignore", "eslint-disable",
		"eslint-enable", "eslint-env", "istanbul ignore", "jscs:", "jshint ", "jslint ", "oxlint-", "prettier-ignore",
		"tslint:", "v8 ignore",
	}
	cDirectives = []string{
		"GCOVR_EXCL_", "IWYU pragma:", "LCOV_EXCL_", "NOLINT", "NOLINTBEGIN", "NOLINTEND", "NOLINTNEXTLINE",
		"clang-format", "clang-tidy", "cppcheck-suppress",
	}
	shellDirectives = []string{"shellcheck ", "shfmt:"}
)

// languageDirectives lists, per format, the prefixes of comments that build,
// lint, type-check, format and coverage tools read as instructions. The
// spellings are exact and case-sensitive; there is no pattern matching. The
// list is documented in docs/inputs.md and must change together with it.
var languageDirectives = map[document.Format][]string{
	document.Go:         {"#nosec", "+build", "go:", "line ", "lint:", "nolint"},
	document.JavaScript: scriptDirectives,
	document.TypeScript: scriptDirectives,
	document.TSX:        scriptDirectives,
	document.Python: {
		"flake8:", "fmt:", "isort:", "mypy:", "noqa", "nosec", "pragma:", "pylint:", "pyright:", "pytype:", "ruff:",
		"type: ignore", "yapf:",
	},
	document.Java:       {"$NON-NLS", "@formatter:", "CHECKSTYLE", "NOPMD", "NOSONAR", "checkstyle:", "noinspection", "spotless:"},
	document.C:          cDirectives,
	document.CPP:        cDirectives,
	document.CSharp:     {"<auto-generated", "ReSharper "},
	document.YAML:       {"checkov:", "prettier-ignore", "renovate:", "yaml-language-server:", "yamllint "},
	document.Bash:       shellDirectives,
	document.Shell:      shellDirectives,
	document.Zsh:        shellDirectives,
	document.Fish:       shellDirectives,
	document.PowerShell: shellDirectives,
}

// toolDirective reports whether a comment's text is an instruction for a tool
// rather than prose. Only the fixed prefixes for the format and the common
// prefixes count; a sentence that mentions a tool is not a directive.
func toolDirective(format document.Format, content string) bool {
	content = strings.TrimSpace(content)
	for _, prefix := range commonDirectives {
		if directivePrefix(content, prefix) {
			return true
		}
	}
	for _, prefix := range languageDirectives[format] {
		if directivePrefix(content, prefix) {
			return true
		}
	}
	return false
}

// directivePrefix reports whether content starts with prefix as a whole word.
// A prefix that ends in a letter or digit must not continue into another one,
// so "nolint" matches "nolint:errcheck" and not "nolinting".
func directivePrefix(content, prefix string) bool {
	rest, found := strings.CutPrefix(content, prefix)
	if !found {
		return false
	}
	return rest == "" || !wordByte(prefix[len(prefix)-1]) || !wordByte(rest[0])
}

func wordByte(b byte) bool {
	return ('a' <= b && b <= 'z') || ('A' <= b && b <= 'Z') || ('0' <= b && b <= '9')
}
