#!/usr/bin/env bash
# Acquire published document sets for the research corpus.
#
# Document sets are acquired outside the product. This script fetches each
# text from the RFC Editor. It reads the publication month from the index
# and from the document header. It removes page furniture and writes an
# acquisition record. The offline corpus tool then applies the selection
# rules. Every network result is written down.
#
# A set enters the corpus as one snapshot. Its texts sit at the top level
# of a set directory. A LICENSE holds the copyright sections of the texts.
# The commit identity digests the raw texts. A date never proves
# authorship; the record names the two statements that agree on it.
set -euo pipefail
cd "$(dirname "$0")/.."
root=$PWD

sources=research/acquisition/sources-documents-v1.json
cohort=historical
work=${UNSWELL_ACQUISITION_WORK:-$HOME/.cache/unswell/acquisition/work}
output=
boundary=
only=
dry_run=0

usage() {
  printf 'Usage: bash scripts/acquire-documents.sh [--sources FILE] [--cohort historical|historical-YYYY] [--work DIR] [--output DIR] [--boundary YYYY-MM-DD] [--only NAME] [--dry-run]\n' >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sources)
      sources=$2
      shift 2
      ;;
    --cohort)
      cohort=$2
      shift 2
      ;;
    --work)
      work=$2
      shift 2
      ;;
    --output)
      output=$2
      shift 2
      ;;
    --boundary)
      boundary=$2
      shift 2
      ;;
    --only)
      only=$2
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

for tool in curl jq; do
  command -v "$tool" >/dev/null || {
    printf '%s is required.\n' "$tool" >&2
    exit 1
  }
done

case "$cohort" in
  historical | historical-2012 | historical-2016 | historical-2018) ;;
  *)
    printf 'cohort must be historical, historical-2012, historical-2016, or historical-2018\n' >&2
    exit 2
    ;;
esac
if [[ -z "$output" ]]; then
  output=artifacts/acquisition/$cohort
fi
if [[ -z "$boundary" ]]; then
  boundary=$(jq -r '.boundary' "$sources")
fi
seed=$(jq -r '.protocol' "$sources")
index_url=$(jq -r '.publisher.index' "$sources")
documents_url=$(jq -r '.publisher.documents' "$sources")
mkdir -p "$work/documents" "$output/records" "$output/shards" "$output/results"
corpus_tool=$root/artifacts/corpus/corpus
if [[ "$dry_run" == 0 ]]; then
  mkdir -p "$root/artifacts/corpus"
  (cd research/annotation && CGO_ENABLED=0 go build -o "$corpus_tool" ./cmd/corpus)
fi

# Selection rules are fixed here, before any file is read, and repeated in
# every record so a reviewer sees them next to the result. A set has no
# documentation root: its texts sit at the top level, where the corpus tool
# reads them as documentation. One text is one shard.
excluded_segments='["vendor","node_modules","third_party","thirdparty","external","test","tests","testdata","fixtures",".github","dist","build","target","site-packages"]'
excluded_basenames='["LICENSE","LICENCE","COPYING","NOTICE","CODE_OF_CONDUCT","PATENTS","AUTHORS","CONTRIBUTORS","MAINTAINERS"]'
generated_markers='["DO NOT EDIT","@generated","Code generated","Autogenerated","autogenerated","GENERATED FILE"]'
translation_hints='["ja","zh","zh-cn","zh-tw","ko","ru","de","fr","es","pt","pt-br","it","i18n","locale","locales","translations","translation"]'
months='January|February|March|April|May|June|July|August|September|October|November|December'

digest() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}

# fetch downloads a URL into a file once and prints ok or failed; a cached
# file is reused, and a failed request leaves no file behind.
fetch() {
  local url=$1 target=$2
  if [[ -s "$target" ]]; then
    printf 'ok'
    return 0
  fi
  if curl --silent --fail --location --max-time 120 -H 'User-Agent: unswell-research (research@stokaro)' -o "$target.part" "$url"; then
    mv "$target.part" "$target"
    printf 'ok'
  else
    rm -f "$target.part"
    printf 'failed'
  fi
}

month_number() {
  case "$1" in
    January) printf '01' ;;
    February) printf '02' ;;
    March) printf '03' ;;
    April) printf '04' ;;
    May) printf '05' ;;
    June) printf '06' ;;
    July) printf '07' ;;
    August) printf '08' ;;
    September) printf '09' ;;
    October) printf '10' ;;
    November) printf '11' ;;
    December) printf '12' ;;
  esac
}

# last_day prints the last day of a month, so a publication month yields the
# latest date the text can carry.
last_day() {
  local year=$1 month=$2
  case "$month" in
    01 | 03 | 05 | 07 | 08 | 10 | 12) printf '31' ;;
    04 | 06 | 09 | 11) printf '30' ;;
    02)
      if ((year % 4 == 0 && (year % 100 != 0 || year % 400 == 0))); then
        printf '29'
      else
        printf '28'
      fi
      ;;
  esac
}

# index_month prints the publication month the publisher's index gives a
# document, or nothing when the index has no dated entry for it.
index_month() {
  local number=$1
  tr -d '\r' <"$index" | awk -v number="$number" '$0 ~ "^" number " " { p = 1 } p && /^$/ { exit } p { print }' |
    grep -oE "($months) [0-9]{4}\." | head -n 1 | tr -d '.' || true
}

# header_month prints the publication month the document's own header
# states, or nothing when the header carries none.
header_month() {
  head -n 24 "$1" | tr -d '\r' | grep -oE "($months) [0-9]{4} *$" | head -n 1 | sed 's/ *$//' || true
}

# strip_furniture writes a text without page headers, footers, form feeds,
# and the dotted table of contents, so the prose paragraphs stay whole.
strip_furniture() {
  tr -d '\f\r' <"$1" | awk -v months="$months" '
    $0 ~ "^RFC [0-9]+ .*(" months ") [0-9][0-9][0-9][0-9]$" { next }
    /\[Page [0-9]+\]$/ { next }
    /\.\.\.\.+ *[0-9]+$/ { next }
    { print }
  ' | cat -s >"$2"
}

# copyright_sections prints the copyright sections of a text: the notice
# after the status paragraph and, in older texts, the full statement at the
# end.
copyright_sections() {
  awk '
    /^Copyright Notice$/ || /Full Copyright Statement$/ { p = 1; print; next }
    /^[^ ]/ { p = 0 }
    p { print }
  ' "$1"
}

log=$output/acquisition-log.json
if [[ ! -s "$log" ]]; then
  printf '[]' >"$log"
fi
record_status() {
  local name=$1 status=$2 detail=$3
  jq --arg name "$name" --arg status "$status" --argjson detail "$detail" \
    '[.[] | select(.name != $name)] + [{"name": $name, "status": $status} + $detail]' "$log" >"$log.tmp"
  mv "$log.tmp" "$log"
}

index=$work/documents/rfc-index.txt
rm -f "$index"
fetched=$(fetch "$index_url" "$index")
if [[ "$fetched" != ok ]]; then
  printf 'the publisher index could not be fetched: %s\n' "$index_url" >&2
  exit 1
fi
index_digest=$(digest "$index")
fetched_on=$(date -u +%Y-%m-%d)

count=$(jq '.sets | length' "$sources")
for ((i = 0; i < count; i++)); do
  entry=$(jq -c ".sets[$i]" "$sources")
  name=$(jq -r '.name' <<<"$entry")
  if [[ -n "$only" && "$name" != "$only" ]]; then
    continue
  fi
  slug=${name//\//__}
  dir=$work/$cohort/$slug
  mkdir -p "$dir"
  rm -f "$dir"/rfc*.txt "$dir/LICENSE"
  evidence="Index $index_url (sha256 $index_digest, fetched $fetched_on)."
  identity=""
  latest=""
  ok=1
  numbers=$(jq -r '.documents[]' <<<"$entry")
  while read -r number; do
    raw=$work/documents/rfc$number.txt
    fetched=$(fetch "$documents_url/rfc$number.txt" "$raw")
    if [[ "$fetched" != ok ]]; then
      detail=$(jq -n --arg n "$number" '{document: $n}')
      record_status "$name" fetch_failed "$detail"
      printf 'fetch failed: %s rfc%s\n' "$name" "$number"
      ok=0
      break
    fi
    indexed=$(index_month "$number")
    stated=$(header_month "$raw")
    if [[ -z "$indexed" || "$indexed" != "$stated" ]]; then
      detail=$(jq -n --arg n "$number" --arg i "$indexed" --arg s "$stated" '{document: $n, index: $i, header: $s}')
      record_status "$name" date_unverified "$detail"
      printf 'date unverified: %s rfc%s (index %s, header %s)\n' "$name" "$number" "${indexed:-none}" "${stated:-none}"
      ok=0
      break
    fi
    year=${indexed##* }
    month=$(month_number "${indexed%% *}")
    date="$year-$month-$(last_day "$year" "$month")"
    if [[ -z "$latest" || "$date" > "$latest" ]]; then
      latest=$date
    fi
    raw_digest=$(digest "$raw")
    identity+="rfc$number $raw_digest"$'\n'
    evidence+=" RFC $number: index entry dated $indexed, header dated $indexed, raw text sha256 $raw_digest."
    strip_furniture "$raw" "$dir/rfc$number.txt"
    {
      printf 'RFC %s\n\n' "$number"
      copyright_sections "$raw"
      printf '\n'
    } >>"$dir/LICENSE"
  done <<<"$numbers"
  if [[ "$ok" == 0 ]]; then
    continue
  fi
  evidence+=" Page headers, footers, form feeds, and the table of contents were removed before extraction."
  commit=$(printf '%s' "$identity" | sort | digest /dev/stdin)
  detail=$(jq -n --arg c "$commit" --arg d "$latest" '{commit: $c, date: $d, confidence: "corroborated"}')
  if [[ "$latest" > "$boundary" ]]; then
    record_status "$name" outside_boundary "$detail"
    printf 'outside boundary: %s dated %s\n' "$name" "$latest"
    continue
  fi
  if [[ "$dry_run" == 1 ]]; then
    record_status "$name" dry_run "$detail"
    printf 'dry run: %s dated %s, commit %s\n' "$name" "$latest" "$commit"
    continue
  fi
  license=$(jq -r '.license' <<<"$entry")
  topic=$(jq -r '.topic' <<<"$entry")
  purpose=$(jq -r '.purpose' <<<"$entry")
  record=$output/records/$slug.json
  jq -n \
    --arg id "$cohort-$slug" --arg seed "$seed" --arg name "$name" --arg commit "$commit" --arg cohort "$cohort" \
    --arg reference "$documents_url" --arg topic "$topic" --arg purpose "$purpose" --arg license "$license" \
    --arg date "$latest" --arg evidence "$evidence" \
    --argjson segments "$excluded_segments" --argjson basenames "$excluded_basenames" \
    --argjson markers "$generated_markers" --argjson hints "$translation_hints" \
    -f scripts/acquire-documents.jq >"$record"
  result=$output/results/$slug.result.json
  if ! "$corpus_tool" acquire --root "$dir" --record "$record" >"$result" 2>"$output/results/$slug.acquire.log"; then
    record_status "$name" acquire_failed "$detail"
    printf 'acquire failed: %s\n' "$name"
    continue
  fi
  rm -f "$output/shards/$cohort-$slug".json "$output/shards/$cohort-$slug"-[0-9][0-9][0-9].json
  shard_count=$(jq '.manifests | length' "$result")
  for ((s = 0; s < shard_count; s++)); do
    shard_id=$(jq -r ".manifests[$s].id" "$result")
    jq ".manifests[$s]" "$result" >"$output/shards/$shard_id.json"
  done
  selected=$(jq '.selected' "$result")
  excluded=$(jq '.excluded | length' "$result")
  detail=$(jq -n --arg c "$commit" --arg d "$latest" --argjson s "$selected" --argjson e "$excluded" --argjson n "$shard_count" \
    '{commit: $c, date: $d, confidence: "corroborated", selected: $s, excluded: $e, shards: $n}')
  record_status "$name" acquired "$detail"
  printf 'acquired %s (%s): %s texts in %s shards, %s excluded\n' "$name" "$latest" "$selected" "$shard_count" "$excluded"
done
printf 'log: %s\n' "$log"
