#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
root=$PWD

# Historical sources are acquired outside the product: this script clones each
# pinned snapshot, asks an independent registry or release record for the
# publication date, writes an acquisition record, and lets the offline corpus
# tool apply the selection rules. Every network result is written down.
# Checkouts stay outside the repository: a cloned tree inside it would join
# the root Go module and the module policy.
sources=research/acquisition/sources-v1.json
work=${UNSWELL_ACQUISITION_WORK:-$HOME/.cache/unswell/acquisition/work}
output=
cohort=historical
boundary=
dry_run=0
only=

# Cohort windows follow the protocol: historical snapshots are dated on or
# before the boundary, contemporary snapshots on or after the public ChatGPT
# release; a snapshot between the two belongs to neither and is skipped.
contemporary_start=2022-11-30

usage() {
  printf 'Usage: bash scripts/acquire-corpus.sh [--sources FILE] [--cohort historical|historical-YYYY|contemporary] [--work DIR] [--output DIR] [--boundary YYYY-MM-DD] [--only NAME] [--dry-run]\n' >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --sources)
      sources=$2
      shift 2
      ;;
    --work)
      work=$2
      shift 2
      ;;
    --output)
      output=$2
      shift 2
      ;;
    --cohort)
      cohort=$2
      shift 2
      ;;
    --boundary)
      boundary=$2
      shift 2
      ;;
    --only)
      only=$2
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

for tool in git curl jq; do
  command -v "$tool" >/dev/null || {
    printf '%s is required.\n' "$tool" >&2
    exit 1
  }
done

case "$cohort" in
  historical | historical-2012 | historical-2016 | historical-2018 | contemporary) ;;
  *)
    printf 'cohort must be historical, historical-2012, historical-2016, historical-2018, or contemporary\n' >&2
    exit 2
    ;;
esac
if [[ -z "$output" ]]; then
  output=artifacts/acquisition/$cohort
fi
if [[ -z "$boundary" ]]; then
  boundary=$(jq -r '.boundary' "$sources")
fi
seed=$(jq -r '.protocol' "$sources")
mkdir -p "$work" "$output/records" "$output/shards" "$output/results"
corpus_tool=$root/artifacts/corpus/corpus
if [[ "$dry_run" == 0 ]]; then
  mkdir -p "$root/artifacts/corpus"
  (cd research/annotation && CGO_ENABLED=0 go build -o "$corpus_tool" ./cmd/corpus)
fi

# Selection rules are fixed here, before any file is read, and repeated in
# every record so a reviewer sees them next to the result.
document_roots='["docs","doc","documentation","guide","guides","wiki"]'
excluded_segments='["vendor","node_modules","third_party","thirdparty","external","test","tests","testdata","fixtures",".github","dist","build","target","site-packages"]'
excluded_basenames='["LICENSE","LICENCE","COPYING","NOTICE","CODE_OF_CONDUCT","PATENTS","AUTHORS","CONTRIBUTORS","MAINTAINERS"]'
generated_markers='["DO NOT EDIT","@generated","Code generated","Autogenerated","autogenerated","GENERATED FILE"]'
translation_hints='["ja","zh","zh-cn","zh-tw","ko","ru","de","fr","es","pt","pt-br","it","i18n","locale","locales","translations","translation"]'

extensions_for() {
  case "$1" in
    go) printf '[".go"]' ;;
    python) printf '[".py"]' ;;
    javascript) printf '[".js",".ts",".tsx"]' ;;
    rust) printf '[".rs"]' ;;
    java) printf '[".java"]' ;;
    c) printf '[".c",".h"]' ;;
    cpp) printf '[".cpp",".cc",".hpp",".h"]' ;;
    csharp) printf '[".cs"]' ;;
    shell) printf '[".sh",".bash"]' ;;
    powershell) printf '[".ps1",".psm1"]' ;;
    *) printf '[]' ;;
  esac
}

# fetch prints the body of a record, or nothing when the request fails; a
# failed request leaves the snapshot vcs_only instead of stopping the run.
fetch() {
  local url=$1 body
  if [[ -n "${GITHUB_TOKEN:-}" && "$url" == https://api.github.com/* ]]; then
    body=$(curl --silent --fail --max-time 60 -H "Authorization: Bearer $GITHUB_TOKEN" -H 'User-Agent: unswell-research' "$url" || true)
  else
    body=$(curl --silent --fail --max-time 60 -H 'User-Agent: unswell-research (research@stokaro)' "$url" || true)
  fi
  printf '%s' "$body"
}

# publication_date prints the date an independent record gives the version,
# or nothing when the record cannot be read.
publication_date() {
  local entry=$1 name=$2 tag=$3 kind package version group artifact body stamp
  kind=$(jq -r '.registry.kind' <<<"$entry")
  package=$(jq -r '.registry.package // empty' <<<"$entry")
  version=$(jq -r '.registry.version // empty' <<<"$entry")
  case "$kind" in
    pypi)
      body=$(fetch "https://pypi.org/pypi/$package/$version/json")
      jq -r '[.urls[].upload_time_iso_8601] | min // empty | .[0:10]' <<<"$body"
      ;;
    npm)
      body=$(fetch "https://registry.npmjs.org/$package")
      jq -r --arg v "$version" '.time[$v] // empty | .[0:10]' <<<"$body"
      ;;
    crates)
      body=$(fetch "https://crates.io/api/v1/crates/$package/$version")
      jq -r '.version.created_at // empty | .[0:10]' <<<"$body"
      ;;
    maven)
      # Maven Central publishes the POM with the upload time as Last-Modified.
      group=$(jq -r '.registry.group' <<<"$entry")
      artifact=$(jq -r '.registry.artifact' <<<"$entry")
      body=$(curl --silent --fail --head --max-time 60 -H 'User-Agent: unswell-research' \
        "https://repo1.maven.org/maven2/${group//.//}/$artifact/$version/$artifact-$version.pom" || true)
      stamp=$(sed -n 's/^[Ll]ast-[Mm]odified: //p' <<<"$body")
      http_date_to_iso "${stamp//$'\r'/}"
      ;;
    github-release)
      body=$(fetch "https://api.github.com/repos/$name/releases/tags/$tag")
      jq -r '.published_at // empty | .[0:10]' <<<"$body"
      ;;
    github-release-latest)
      body=$(fetch "https://api.github.com/repos/$name/releases/latest")
      jq -r '.published_at // empty | .[0:10]' <<<"$body"
      ;;
    *)
      printf ''
      ;;
  esac
}

# graphql_tags prints one page of the repository's tags with their commit
# dates, newest commit first, as tab-separated lines, followed by one line
# "next <cursor>" when another page exists. It needs GITHUB_TOKEN.
graphql_tags() {
  local owner=$1 repo=$2 cursor=$3 query body
  if [[ -z "${GITHUB_TOKEN:-}" ]]; then
    return 0
  fi
  # The dollar signs are GraphQL variables, bound through the JSON body.
  # shellcheck disable=SC2016
  query='query($owner:String!, $name:String!, $cursor:String) { repository(owner:$owner, name:$name) {'
  # shellcheck disable=SC2016
  query+=' refs(refPrefix:"refs/tags/", first:100, after:$cursor, orderBy:{field:TAG_COMMIT_DATE, direction:DESC}) {'
  query+=' pageInfo { hasNextPage endCursor } nodes { name target { __typename ... on Commit { committedDate }'
  query+=' ... on Tag { target { ... on Commit { committedDate } } } } } } } }'
  body=$(jq -n --arg q "$query" --arg owner "$owner" --arg name "$repo" --arg cursor "$cursor" \
    '{query: $q, variables: {owner: $owner, name: $name, cursor: (if $cursor == "" then null else $cursor end)}}' |
    curl --silent --fail --max-time 60 -H "Authorization: Bearer $GITHUB_TOKEN" -H 'User-Agent: unswell-research' \
      -H 'Content-Type: application/json' --data @- https://api.github.com/graphql || true)
  jq -r '.data.repository.refs as $r | ($r.nodes[] | [.name, (.target.committedDate // .target.target.committedDate // "")] | @tsv),
    (if $r.pageInfo.hasNextPage then "next\t" + $r.pageInfo.endCursor else empty end)' <<<"$body" 2>/dev/null || true
}

# tag_before prints the newest release tag whose commit is dated on or before
# the boundary, then a tab and its version. A release tag is an optional
# prefix from the entry, an optional "v", and a dotted version; a PyPI-style
# beta such as 18.9b0 counts only when the repository has no other release
# tag before the boundary. The walk stops at the first match, because tags
# arrive newest commit first.
tag_before() {
  local name=$1 prefix=$2 owner=${1%%/*} repo=${1##*/} cursor="" tag date stable="" beta="" listing
  local pattern="^(${prefix})?v?([0-9]+(\.[0-9]+)+)$" beta_pattern="^(${prefix})?v?([0-9]+(\.[0-9]+)*b[0-9]+)$"
  listing=$(mktemp)
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    graphql_tags "$owner" "$repo" "$cursor" >"$listing"
    cursor=""
    while IFS=$'\t' read -r tag date; do
      if [[ "$tag" == next ]]; then
        cursor=$date
        continue
      fi
      if [[ -z "$tag" || -z "$date" || "${date:0:10}" > "$boundary" ]]; then
        continue
      fi
      if [[ -z "$stable" && "$tag" =~ $pattern ]]; then
        stable=$tag$'\t'${BASH_REMATCH[2]}
      elif [[ -z "$beta" && "$tag" =~ $beta_pattern ]]; then
        beta=$tag$'\t'${BASH_REMATCH[2]}
      fi
    done <"$listing"
    if [[ -n "$stable" || -z "$cursor" ]]; then
      break
    fi
  done
  rm -f "$listing"
  printf '%s' "${stable:-$beta}"
}

# http_date_to_iso converts an HTTP date such as "Fri, 04 Oct 2019 18:55:00 GMT"
# to YYYY-MM-DD, or prints nothing for any other input.
http_date_to_iso() {
  local day month year number
  read -r _ day month year _ <<<"$1"
  case "$month" in
    Jan) number=01 ;; Feb) number=02 ;; Mar) number=03 ;; Apr) number=04 ;;
    May) number=05 ;; Jun) number=06 ;; Jul) number=07 ;; Aug) number=08 ;;
    Sep) number=09 ;; Oct) number=10 ;; Nov) number=11 ;; Dec) number=12 ;;
    *) printf '' && return 0 ;;
  esac
  if [[ "$year" =~ ^[0-9]{4}$ && "$day" =~ ^[0-9]{2}$ ]]; then
    printf '%s-%s-%s' "$year" "$number" "$day"
  fi
}

# notice_file prints the first retained notice file of a checkout, or nothing.
# Names are compared exactly against the directory listing, so a file named
# "license" on a case-insensitive file system is reported with its own name.
notice_file() {
  local dir=$1 candidate entry
  local -a entries=("$dir"/*)
  for candidate in LICENSE LICENSE.txt LICENSE.md LICENCE COPYING LICENSE.MIT LICENSE-MIT LICENSE-APACHE LICENSE.rst license UNLICENSE; do
    for entry in "${entries[@]}"; do
      if [[ "${entry##*/}" == "$candidate" && -f "$entry" ]]; then
        printf '%s' "$candidate"
        return 0
      fi
    done
  done
  printf ''
}

# days_between prints the absolute number of days between two YYYY-MM-DD dates.
days_between() {
  jq -n --arg a "$1" --arg b "$2" '(($a | strptime("%Y-%m-%d") | mktime) - ($b | strptime("%Y-%m-%d") | mktime)) / 86400 | fabs | floor'
}

# The log keeps one entry per source. A full run starts it afresh; a run
# limited to one source replaces that source's entry and keeps the rest.
log=$output/acquisition-log.json
if [[ -z "$only" || ! -f "$log" ]]; then
  printf '[]' >"$log"
fi
record_status() {
  local name=$1 status=$2 detail=$3
  jq --arg name "$name" --arg status "$status" --argjson detail "$detail" \
    '[.[] | select(.name != $name)] + [{"name": $name, "status": $status} + $detail]' "$log" >"$log.tmp"
  mv "$log.tmp" "$log"
}

count=$(jq '.sources | length' "$sources")
for ((i = 0; i < count; i++)); do
  entry=$(jq -c ".sources[$i]" "$sources")
  name=$(jq -r '.name' <<<"$entry")
  if [[ -n "$only" && "$name" != "$only" ]]; then
    continue
  fi
  url=$(jq -r '.url' <<<"$entry")
  tag=$(jq -r '.tag' <<<"$entry")
  ecosystem=$(jq -r '.ecosystem' <<<"$entry")
  license=$(jq -r '.license' <<<"$entry")
  slug=${name//\//__}
  checkout=$work/$cohort/$slug
  if [[ "$dry_run" == 1 ]]; then
    printf 'would clone %s at %s into %s\n' "$url" "$tag" "$checkout"
    continue
  fi
  # A source that names no tag takes the latest published release, resolved
  # from the same record that dates it; the resolved tag is logged. A source
  # tagged "before" takes the newest release tag committed on or before the
  # boundary, and its version corroborates it against the entry's registry.
  if [[ "$tag" == latest ]]; then
    body=$(fetch "https://api.github.com/repos/$name/releases/latest")
    tag=$(jq -r '.tag_name // empty' <<<"$body")
    if [[ -z "$tag" ]]; then
      record_status "$name" no_latest_release '{}'
      printf 'no latest release: %s\n' "$name"
      continue
    fi
  elif [[ "$tag" == before ]]; then
    tag_prefix=$(jq -r '.registry.tag_prefix // empty' <<<"$entry")
    resolved=$(tag_before "$name" "$tag_prefix")
    tag=${resolved%%$'\t'*}
    version=${resolved#*$'\t'}
    if [[ -z "$tag" ]]; then
      record_status "$name" no_release_before_boundary '{}'
      printf 'no release tag before %s: %s\n' "$boundary" "$name"
      continue
    fi
    entry=$(jq --arg v "$version" '.registry.version = $v' <<<"$entry")
    printf 'resolved %s before %s: %s (version %s)\n' "$name" "$boundary" "$tag" "$version"
  fi
  if [[ ! -d "$checkout/.git" ]]; then
    if ! git clone --quiet --depth 1 --branch "$tag" "$url" "$checkout" 2>"$output/results/$slug.clone.log"; then
      record_status "$name" clone_failed '{}'
      printf 'clone failed: %s %s\n' "$name" "$tag"
      continue
    fi
  fi
  commit=$(git -C "$checkout" rev-parse HEAD)
  commit_stamp=$(git -C "$checkout" log -1 --format=%cI)
  commit_date=${commit_stamp:0:10}
  kind=$(jq -r '.registry.kind' <<<"$entry")
  # A record corroborates the commit only when the two dates agree within
  # 90 days; a release object created long after the tag does not date it.
  published=$(publication_date "$entry" "$name" "$tag")
  gap=
  if [[ "$published" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    gap=$(days_between "$published" "$commit_date")
  fi
  if [[ -n "$gap" && "$gap" -le 90 ]]; then
    confidence=corroborated
    snapshot_date=$published
    evidence="$kind record dates the release $published; commit $commit is dated $commit_date"
  elif [[ -n "$gap" ]]; then
    confidence=vcs_only
    snapshot_date=$commit_date
    evidence="commit $commit is dated $commit_date; the $kind record dates the release $published, $gap days apart, and does not corroborate the commit"
  else
    confidence=vcs_only
    snapshot_date=$commit_date
    evidence="commit $commit is dated $commit_date; no independent publication record was read"
  fi
  detail=$(jq -n --arg c "$commit" --arg d "$snapshot_date" --arg k "$confidence" --arg t "$tag" '{commit: $c, tag: $t, date: $d, confidence: $k}')
  if [[ "$cohort" == historical* && "$snapshot_date" > "$boundary" ]]; then
    record_status "$name" outside_boundary "$detail"
    printf 'outside boundary: %s dated %s\n' "$name" "$snapshot_date"
    continue
  fi
  if [[ "$cohort" == contemporary && "$snapshot_date" < "$contemporary_start" ]]; then
    record_status "$name" outside_boundary "$detail"
    printf 'before the contemporary window: %s dated %s\n' "$name" "$snapshot_date"
    continue
  fi
  notice=$(notice_file "$checkout")
  if [[ -z "$notice" ]]; then
    record_status "$name" notice_missing "$detail"
    printf 'no notice file: %s\n' "$name"
    continue
  fi
  topic=$(jq -r '.topic' <<<"$entry")
  purpose=$(jq -r '.purpose' <<<"$entry")
  extensions=$(extensions_for "$ecosystem")
  record=$output/records/$slug.json
  jq -n \
    --arg id "$cohort-$slug" --arg seed "$seed" --arg name "$name" --arg commit "$commit" --arg cohort "$cohort" \
    --arg reference "https://github.com/$name/blob/$commit" --arg topic "$topic" \
    --arg purpose "$purpose" --arg ecosystem "$ecosystem" --arg license "$license" \
    --arg notice "$notice" --arg date "$snapshot_date" --arg confidence "$confidence" --arg evidence "$evidence" \
    --argjson roots "$document_roots" --argjson extensions "$extensions" \
    --argjson segments "$excluded_segments" --argjson basenames "$excluded_basenames" \
    --argjson markers "$generated_markers" --argjson hints "$translation_hints" \
    '{
      version: "unswell-corpus-acquisition-v1",
      manifest: {id: $id, seed: $seed,
        weights: {training: 5000, development: 1500, calibration: 1500, final_test: 2000},
        extraction_policy: {contexts: ["comment", "string", "paragraph", "heading", "list-item", "table-cell"], languages: {}, exceptions: []},
        unit_kinds: ["sentence", "paragraph", "fragment"]},
      repository: {name: $name, reference: $reference, commit: $commit, topic: $topic, purpose: $purpose, ecosystem: $ecosystem,
        origin: {label: "unknown", scope: "repository", evidence: "Dated snapshot; no unit-level authorship record.", generation_record: ""},
        rights: {license: $license, evidence: ("Retained notice " + $notice + " at commit " + $commit), allowed_uses: ["annotation", "evaluation", "training"]},
        notices: [$notice],
        snapshot: {date: $date, confidence: $confidence, evidence: $evidence, cohort: $cohort}},
      selection: {max_sources: 400, shard_sources: 40, shard_bytes: 393216, max_source_bytes: 1048576, document_roots: $roots,
        source_extensions: $extensions,
        excluded_segments: $segments, excluded_basenames: $basenames, generated_markers: $markers, translation_hints: $hints}
    }' >"$record"
  result=$output/results/$slug.result.json
  if ! "$corpus_tool" acquire --root "$checkout" --record "$record" >"$result" 2>"$output/results/$slug.acquire.log"; then
    record_status "$name" acquire_failed "$detail"
    printf 'acquire failed: %s\n' "$name"
    continue
  fi
  # A repository with many sources spans numbered shards; each is one file
  # named after its manifest ID, and stale shards of the same repository go.
  rm -f "$output/shards/$cohort-$slug".json "$output/shards/$cohort-$slug"-[0-9][0-9][0-9].json
  shard_count=$(jq '.manifests | length' "$result")
  for ((s = 0; s < shard_count; s++)); do
    shard_id=$(jq -r ".manifests[$s].id" "$result")
    jq ".manifests[$s]" "$result" >"$output/shards/$shard_id.json"
  done
  selected=$(jq '.selected' "$result")
  excluded=$(jq '.excluded | length' "$result")
  detail=$(jq -n --arg c "$commit" --arg d "$snapshot_date" --arg k "$confidence" --arg t "$tag" --argjson s "$selected" --argjson e "$excluded" \
    --argjson n "$shard_count" '{commit: $c, tag: $t, date: $d, confidence: $k, selected: $s, excluded: $e, shards: $n}')
  record_status "$name" acquired "$detail"
  printf 'acquired %s at %s (%s, %s): %s sources in %s shards, %s excluded\n' "$name" "$tag" "$snapshot_date" "$confidence" "$selected" "$shard_count" "$excluded"
done
printf 'log: %s\n' "$log"
