package corpus_test

import (
	"context"
	"encoding/json"
	"strings"
	"testing"

	qt "github.com/frankban/quicktest"

	"github.com/stokaro/unswell/extract"
	"github.com/stokaro/unswell/research/annotation"
	"github.com/stokaro/unswell/research/annotation/corpus"
)

func acquisitionRecord() corpus.Acquisition {
	return corpus.Acquisition{Version: corpus.AcquisitionVersion,
		Manifest: corpus.AcquisitionHeader{ID: "shard-fixture", Seed: "unswell-research-v1",
			Weights: corpus.Weights{Training: 5000, Development: 1500, Calibration: 1500, FinalTest: 2000},
			Policy:  extract.Policy{}, UnitKinds: []string{"sentence", "paragraph", "fragment"}},
		Repository: corpus.RepositoryRecord{Name: "example/fixture", Reference: "https://example.invalid/fixture/blob/abc123",
			Commit: "abc123", Topic: "fixtures", Purpose: "Exercise the acquisition rules", Ecosystem: "go",
			Origin:   annotation.Origin{Label: "unknown", Scope: "repository", Evidence: "Historical snapshot; no unit-level authorship record."},
			Rights:   annotation.Rights{License: "MIT", Evidence: "LICENSE at the pinned commit", AllowedUses: []string{"annotation", "evaluation"}},
			Notices:  []string{"LICENSE"},
			Snapshot: corpus.Snapshot{Date: "2019-06-30", Confidence: "corroborated", Evidence: "Registry release date", Cohort: "historical"}},
		Selection: corpus.SelectionRules{MaxSources: 10, ShardSources: 10, ShardBytes: 65536, MaxSourceBytes: 4096,
			DocumentRoots:    []string{"docs"},
			SourceExtensions: []string{".go"}, ExcludedSegments: []string{"vendor", "testdata"},
			ExcludedBasenames: []string{"LICENSE", "CODE_OF_CONDUCT"}, GeneratedMarkers: []string{"DO NOT EDIT"},
			TranslationHints: []string{"ja", "zh-cn"}}}
}

func checkout() map[string][]byte {
	prose := "The cache retries a failed lookup after the configured delay expires.\n"
	return map[string][]byte{
		"LICENSE":            []byte("MIT License\n"),
		"README.md":          []byte("# Fixture\n\n" + prose),
		"CHANGELOG.md":       []byte("# Changes\n\n- Fixed the retry delay.\n"),
		"CODE_OF_CONDUCT.md": []byte("# Conduct\n\n" + prose),
		"docs/guide.md":      []byte("# Guide\n\n" + prose),
		"docs/ja/guide.md":   []byte("# ガイド\n\n" + prose),
		"notes/other.md":     []byte("# Other\n\n" + prose),
		"main.go":            []byte("// Package main starts the cache.\npackage main\n"),
		"gen.go":             []byte("// Code generated by tool. DO NOT EDIT.\npackage main\n"),
		"vendor/dep/dep.go":  []byte("// Package dep is vendored.\npackage dep\n"),
		"testdata/sample.go": []byte("// Package sample is a fixture.\npackage sample\n"),
		"image.png":          {0x89, 'P', 'N', 'G', 0xff, 0xfe},
		"script.rb":          []byte("# Ruby comment\nputs 1\n"),
		"docs/big.md":        []byte("# Big\n\n" + strings.Repeat(prose, 100)),
	}
}

func TestAcquisitionAppliesPredefinedRules(t *testing.T) {
	c := qt.New(t)
	record := acquisitionRecord()
	loaded, err := corpus.LoadAcquisition(t.Context(), encoded(c, record))
	c.Assert(err, qt.IsNil)
	result, err := corpus.Acquire(t.Context(), loaded, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(result.Version, qt.Equals, corpus.AcquisitionVersion)
	c.Assert(result.Manifests, qt.HasLen, 1)
	c.Assert(result.Manifests[0].ID, qt.Equals, "shard-fixture")
	roles := map[string]string{}
	for _, source := range result.Manifests[0].Sources {
		roles[source.Path] = source.Role
		c.Assert(source.Repository, qt.Equals, "example/fixture")
		c.Assert(source.Reference, qt.Equals, "https://example.invalid/fixture/blob/abc123/"+source.Path)
		c.Assert(source.Origin.Label, qt.Equals, "unknown")
		c.Assert(source.Snapshot.Cohort, qt.Equals, "historical")
		c.Assert(source.Notices, qt.DeepEquals, []corpus.Notice{{Path: "LICENSE", SHA256: hash([]byte("MIT License\n")), Bytes: 12}})
		c.Assert(source.ID, qt.HasLen, 24)
	}
	c.Assert(roles, qt.DeepEquals, map[string]string{"README.md": "readme", "CHANGELOG.md": "release_note",
		"docs/guide.md": "documentation", "main.go": "comment"})
	c.Assert(result.Selected, qt.Equals, 4)
	reasons := map[string]string{}
	for _, item := range result.Excluded {
		reasons[item.Path] = item.Reason
	}
	c.Assert(reasons, qt.DeepEquals, map[string]string{
		"LICENSE": "notice", "CODE_OF_CONDUCT.md": "excluded_basename", "docs/ja/guide.md": "translation_hint",
		"notes/other.md": "unselected_kind", "gen.go": "generated_marker", "vendor/dep/dep.go": "excluded_segment",
		"testdata/sample.go": "excluded_segment", "image.png": "not_utf8", "script.rb": "unselected_kind",
		"docs/big.md": "outside_byte_limit"})
	c.Assert(result.Subsample, qt.IsNil)
	// The manifest plans as one component and its candidates carry the cohort.
	plan, err := corpus.MakePlan(t.Context(), result.Manifests[0])
	c.Assert(err, qt.IsNil)
	c.Assert(plan.Groups, qt.HasLen, 1)
	required, err := corpus.Files(t.Context(), plan)
	c.Assert(err, qt.IsNil)
	files := map[string][]byte{}
	for _, file := range required {
		files[file.Path] = checkout()[file.Path]
	}
	artifact, err := corpus.Build(t.Context(), plan, files)
	c.Assert(err, qt.IsNil)
	c.Assert(len(artifact.Units) > 0, qt.IsTrue)
	for _, candidate := range artifact.Units {
		c.Assert(candidate.Cohort, qt.Equals, "historical")
	}
	// The same checkout gives the same manifest.
	again, err := corpus.Acquire(t.Context(), loaded, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(again, qt.DeepEquals, result)
}

func TestAcquisitionSubsamplesToTheCapWithARecordedSeed(t *testing.T) {
	c := qt.New(t)
	record := acquisitionRecord()
	record.Selection.MaxSources = 2
	result, err := corpus.Acquire(t.Context(), record, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(result.Manifests[0].Sources, qt.HasLen, 2)
	c.Assert(result.Subsample, qt.IsNotNil)
	c.Assert(result.Subsample.Before, qt.Equals, 4)
	c.Assert(result.Subsample.After, qt.Equals, 2)
	c.Assert(result.Subsample.Dropped, qt.HasLen, 2)
	c.Assert(result.Subsample.Seed, qt.Equals, "unswell-research-v1\x00example/fixture")
	dropped := 0
	for _, item := range result.Excluded {
		if item.Reason == "seeded_subsample" {
			dropped++
		}
	}
	c.Assert(dropped, qt.Equals, 2)
	again, err := corpus.Acquire(t.Context(), record, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(again.Subsample.Dropped, qt.DeepEquals, result.Subsample.Dropped)
}

func TestAcquisitionRejectsBadRecordsAndMissingNotices(t *testing.T) {
	c := qt.New(t)
	for _, edit := range []func(*corpus.Acquisition){
		func(a *corpus.Acquisition) { a.Version = "future" },
		func(a *corpus.Acquisition) { a.Repository.Commit = "" },
		func(a *corpus.Acquisition) { a.Repository.Notices = nil },
		func(a *corpus.Acquisition) { a.Repository.Notices = []string{"../LICENSE"} },
		func(a *corpus.Acquisition) { a.Selection.MaxSources = 0 },
		func(a *corpus.Acquisition) { a.Selection.ShardSources = 0 },
		func(a *corpus.Acquisition) { a.Selection.ShardBytes = 0 },
		func(a *corpus.Acquisition) { a.Selection.MaxSourceBytes = corpus.MaxSourceBytes + 1 },
		func(a *corpus.Acquisition) { a.Manifest.UnitKinds = []string{"document"} },
		func(a *corpus.Acquisition) { a.Selection.SourceExtensions = []string{".go", ".go"} },
	} {
		record := acquisitionRecord()
		edit(&record)
		_, err := corpus.LoadAcquisition(t.Context(), encoded(c, record))
		c.Assert(err, qt.IsNotNil)
	}
	var loose map[string]any
	c.Assert(json.Unmarshal(encoded(c, acquisitionRecord()), &loose), qt.IsNil)
	loose["extra"] = true
	_, err := corpus.LoadAcquisition(t.Context(), encoded(c, loose))
	c.Assert(err, qt.IsNotNil)
	files := checkout()
	delete(files, "LICENSE")
	_, err = corpus.Acquire(t.Context(), acquisitionRecord(), files)
	c.Assert(err, qt.IsNotNil)
	// A record whose snapshot contradicts its origin fails manifest validation.
	record := acquisitionRecord()
	record.Repository.Snapshot.Cohort = "controlled"
	_, err = corpus.Acquire(t.Context(), record, checkout())
	c.Assert(err, qt.IsNotNil)
	empty := acquisitionRecord()
	empty.Selection.SourceExtensions = []string{".rs"}
	empty.Selection.DocumentRoots = nil
	only := map[string][]byte{"LICENSE": []byte("MIT License\n"), "src/lib.go": []byte("// x\npackage x\n")}
	_, err = corpus.Acquire(t.Context(), empty, only)
	c.Assert(err, qt.IsNotNil)
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	_, err = corpus.Acquire(ctx, acquisitionRecord(), checkout())
	c.Assert(err, qt.IsNotNil)
}

func TestAcquisitionExcludesFilesTheExtractorRejects(t *testing.T) {
	c := qt.New(t)
	record := acquisitionRecord()
	record.Selection.SourceExtensions = []string{".go", ".c"}
	files := checkout()
	files["broken.c"] = []byte("/* The parser cannot finish this file. */\nint main( {\n")
	result, err := corpus.Acquire(t.Context(), record, files)
	c.Assert(err, qt.IsNil)
	reasons := map[string]string{}
	for _, item := range result.Excluded {
		reasons[item.Path] = item.Reason
	}
	c.Assert(reasons["broken.c"], qt.Equals, "parse_failure")
	for _, source := range result.Manifests[0].Sources {
		c.Assert(source.Path, qt.Not(qt.Equals), "broken.c")
	}
}

func TestAcquisitionSplitsARepositoryIntoNumberedShards(t *testing.T) {
	c := qt.New(t)
	record := acquisitionRecord()
	record.Selection.ShardSources = 3
	result, err := corpus.Acquire(t.Context(), record, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(result.Selected, qt.Equals, 4)
	c.Assert(result.Manifests, qt.HasLen, 2)
	c.Assert(result.Manifests[0].ID, qt.Equals, "shard-fixture-001")
	c.Assert(result.Manifests[1].ID, qt.Equals, "shard-fixture-002")
	c.Assert(result.Manifests[0].Sources, qt.HasLen, 3)
	c.Assert(result.Manifests[1].Sources, qt.HasLen, 1)
	// Both shards keep the repository key, so a dataset plan joins them.
	shards := map[string][]byte{}
	dataset := corpus.Dataset{Version: corpus.DatasetVersion, ID: "split", Seed: record.Manifest.Seed,
		Weights: record.Manifest.Weights, Policy: record.Manifest.Policy, UnitKinds: record.Manifest.UnitKinds,
		RuleClassesSHA256: hash([]byte("classes"))}
	for _, manifest := range result.Manifests {
		data := encoded(c, manifest)
		path := "shards/" + manifest.ID + ".json"
		shards[path] = data
		dataset.Shards = append(dataset.Shards, corpus.Notice{Path: path, SHA256: hash(data), Bytes: len(data)})
	}
	plan, err := corpus.MakeDatasetPlan(t.Context(), dataset, shards)
	c.Assert(err, qt.IsNil)
	c.Assert(plan.Groups, qt.HasLen, 1)
	c.Assert(plan.Groups[0].Shards, qt.HasLen, 2)
	// Another snapshot of the same repository gets distinct source IDs, so both
	// snapshots can share one dataset and one component.
	later := record
	later.Repository.Commit = "def456"
	later.Manifest.ID = "shard-fixture-later"
	other, err := corpus.Acquire(t.Context(), later, checkout())
	c.Assert(err, qt.IsNil)
	for i := range other.Manifests[0].Sources {
		c.Assert(other.Manifests[0].Sources[i].ID, qt.Not(qt.Equals), result.Manifests[0].Sources[i].ID)
	}
	// A byte budget cuts shards too, and a file above it stands alone.
	record.Selection.ShardSources = 10
	record.Selection.ShardBytes = 120
	result, err = corpus.Acquire(t.Context(), record, checkout())
	c.Assert(err, qt.IsNil)
	c.Assert(len(result.Manifests) >= 2, qt.IsTrue)
	total := 0
	for _, manifest := range result.Manifests {
		size := 0
		for _, source := range manifest.Sources {
			size += source.Bytes
		}
		c.Assert(size <= 120 || len(manifest.Sources) == 1, qt.IsTrue, qt.Commentf("%s: %d bytes", manifest.ID, size))
		total += len(manifest.Sources)
	}
	c.Assert(total, qt.Equals, 4)
}

func TestAcquireDeclaredDocumentRole(t *testing.T) {
	c := qt.New(t)
	record := acquisitionRecord()
	record.Selection.DocumentRole = "specification"
	loaded, err := corpus.LoadAcquisition(t.Context(), encoded(c, record))
	c.Assert(err, qt.IsNil)
	result, err := corpus.Acquire(t.Context(), loaded, checkout())
	c.Assert(err, qt.IsNil)
	roles := map[string]string{}
	for _, source := range result.Manifests[0].Sources {
		roles[source.Path] = source.Role
	}
	// The declared role replaces documentation only; README, change logs, and code keep theirs.
	c.Assert(roles, qt.DeepEquals, map[string]string{"README.md": "readme", "CHANGELOG.md": "release_note",
		"docs/guide.md": "specification", "main.go": "comment"})
	record.Selection.DocumentRole = "poem"
	_, err = corpus.LoadAcquisition(t.Context(), encoded(c, record))
	c.Assert(err, qt.ErrorMatches, ".*unknown document role.*")
}
